version: 0.2

# CodeBuild Buildspec
phases:

  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 125021993355.dkr.ecr.ap-south-1.amazonaws.com
      - echo Downloading .env file from S3...
      - aws s3 cp s3://prod-dexlyn-env/bridgescan-web/.env ./.env  # Replace with your actual S3 bucket name
      
  pre_build:
    commands:
      - echo "Setting IMAGE_TAG with CodeBuild build number..."
      - export IMAGE_TAG=${CODEBUILD_BUILD_NUMBER}  # Using CodeBuild build number as the tag

  build:
    commands:
      - echo "Build started on $(date)"
      - docker build --build-arg PROJECTS="bridgescan" -t 125021993355.dkr.ecr.ap-south-1.amazonaws.com/prod-dexlyn-bridgescan-web:${IMAGE_TAG} -f Dockerfile.bridgescan .

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image with IMAGE_TAG to ECR..."
      - docker push 125021993355.dkr.ecr.ap-south-1.amazonaws.com/prod-dexlyn-bridgescan-web:${IMAGE_TAG}
      - echo "Tagging the IMAGE_TAG as latest locally..."
      - docker tag 125021993355.dkr.ecr.ap-south-1.amazonaws.com/prod-dexlyn-bridgescan-web:${IMAGE_TAG} 125021993355.dkr.ecr.ap-south-1.amazonaws.com/prod-dexlyn-bridgescan-web:latest
      - echo "Pushing the latest tag to ECR..."
      - docker push 125021993355.dkr.ecr.ap-south-1.amazonaws.com/prod-dexlyn-bridgescan-web:latest
      - echo "Creating imagedefinitions.json file..."
      - echo '[{"name":"prod-dexlyn-bridgescan-web","imageUri":"125021993355.dkr.ecr.ap-south-1.amazonaws.com/prod-dexlyn-bridgescan-web:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json